import { Lock } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import type { Outbound } from "@/lib/types"
import { OutboundDetailPanel } from "./outbound-detail-panel"
import { buildOutboundDetails, describeOutboundRoute, type OutboundUsage } from "./outbound-details"

interface ManagedOutboundListProps {
    outbounds: Outbound[]
    usage: Map<string, OutboundUsage>
    defaultTag: string | null
    onOpenRules: () => void
}

// Router rows have no persisted ID. Tag-keyed, read-only disclosures keep them
// inspectable without exposing selection, edit, delete, toggle, or test actions.
export function ManagedOutboundList({ outbounds, usage, defaultTag, onOpenRules }: ManagedOutboundListProps) {
    if (outbounds.length === 0) return null
    return (
        <section aria-label="Managed router outbounds" className="overflow-hidden rounded-xl border bg-card">
            <div className="border-b bg-muted/30 px-4 py-3">
                <h3 className="text-sm font-medium">Router outbounds</h3>
                <p className="mt-1 text-xs text-muted-foreground">Generated by your WAN configuration. These routes cannot be edited or removed here.</p>
            </div>
            <div className="divide-y">
                {outbounds.map(outbound => {
                    const route = describeOutboundRoute(outbound)
                    const isDefault = outbound.tag === defaultTag
                    return (
                        <details key={outbound.tag} className="group px-4 py-3">
                            <summary className="cursor-pointer rounded-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">
                                <span className="ml-1 inline-flex max-w-[calc(100%-1.5rem)] flex-wrap items-center gap-2 align-middle">
                                    <Lock className="h-3.5 w-3.5 shrink-0 text-muted-foreground" aria-hidden="true" />
                                    <span className="break-all font-mono text-sm font-semibold">{outbound.tag}</span>
                                    <Badge variant="secondary" className="text-[10px]">Managed</Badge>
                                    {isDefault && <Badge variant="outline" className="text-[10px]">Default</Badge>}
                                    <span className="text-xs text-muted-foreground">{route}</span>
                                </span>
                            </summary>
                            {outbound.remark && <p className="mt-1 text-xs text-muted-foreground">{outbound.remark}</p>}
                            <div className="mt-4">
                                <OutboundDetailPanel
                                    outbound={outbound}
                                    route={route}
                                    details={buildOutboundDetails(outbound)}
                                    usage={usage.get(outbound.tag) ?? { rules: [], balancers: [] }}
                                    isDefault={isDefault}
                                    onOpenRules={onOpenRules}
                                />
                            </div>
                        </details>
                    )
                })}
            </div>
        </section>
    )
}
