import type { Inbound } from "@/lib/types"
import { Shield, Globe, Zap, Lock, Eye, Wifi, Server, Radio, Waypoints, Network } from "lucide-react"
import type { LucideIcon } from "lucide-react"

export interface InboundPreset {
    id: string
    name: string
    description: string
    /** Stack tokens shown on the card and matched by the template search. */
    tokens: string[]
    icon: LucideIcon
    defaults: Partial<Inbound>
}

const SNIFFING = {
    enabled: true,
    destOverride: ["http", "tls"],
    metadataOnly: false,
    routeOnly: false,
}

const REALITY_DEFAULTS = {
    fingerprint: "chrome",
    dest: "www.google.com:443",
    serverNames: ["www.google.com"],
}

// Order matters: the picker shows the first 8 without a search query. The
// original eight stay first, in their original order; everything after them
// is mapped from XTLS/Xray-examples (plus HTTPUpgrade from the transports
// docs) into the protocols, networks and security modes this panel supports.
export const INBOUND_PRESETS: InboundPreset[] = [
    {
        id: "vless-xhttp",
        name: "VLESS + XHTTP · behind Nginx/CDN",
        description: "Xray listens on localhost; Nginx, Caddy or a CDN terminates TLS in front (Xray-examples VLESS-TLS-SplitHTTP-CaddyNginx, VLESS-XHTTP3-Nginx)",
        tokens: ["xhttp", "none", "127.0.0.1"],
        icon: Globe,
        defaults: {
            protocol: "vless",
            port: 8443,
            listen: "127.0.0.1",
            network: "xhttp",
            security: "none",
            transport_settings: { path: "/", mode: "auto" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-xhttp-tls",
        name: "VLESS + XHTTP + TLS",
        description: "Multiplexed transport with TLS terminated by Xray",
        tokens: ["xhttp", "tls"],
        icon: Zap,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "xhttp",
            security: "tls",
            transport_settings: { path: "/", mode: "auto" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-xhttp-reality",
        name: "VLESS + XHTTP + Reality",
        description: "Best anti-detection: Reality fingerprinting over XHTTP (Xray-examples VLESS-XHTTP-Reality)",
        tokens: ["xhttp", "reality", "vision"],
        icon: Shield,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "xhttp",
            security: "reality",
            vless_settings: { flow: "xtls-rprx-vision" },
            transport_settings: { path: "/", mode: "auto" },
            reality_settings: REALITY_DEFAULTS,
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vmess-ws-tls",
        name: "VMess + WS + TLS",
        description: "Classic VMess over WebSocket with TLS (Xray-examples VMess-Websocket-TLS)",
        tokens: ["ws", "tls"],
        icon: Lock,
        defaults: {
            protocol: "vmess",
            port: 443,
            listen: "0.0.0.0",
            network: "ws",
            security: "tls",
            transport_settings: { path: "/" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "trojan-ws-tls",
        name: "Trojan + WS + TLS",
        description: "Trojan over WebSocket with TLS",
        tokens: ["ws", "tls"],
        icon: Eye,
        defaults: {
            protocol: "trojan",
            port: 443,
            listen: "0.0.0.0",
            network: "ws",
            security: "tls",
            transport_settings: { path: "/" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "shadowsocks",
        name: "Shadowsocks 2022",
        description: "Shadowsocks 2022 with BLAKE3 AES-128-GCM (Xray-examples Shadowsocks-2022)",
        tokens: ["tcp", "2022-aes-128"],
        icon: Wifi,
        defaults: {
            protocol: "shadowsocks",
            port: 8388,
            listen: "0.0.0.0",
            network: "tcp",
            security: "none",
            shadowsocks_settings: { method: "2022-blake3-aes-128-gcm", network: "tcp,udp" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "wireguard",
        name: "WireGuard",
        description: "Kernel-style WireGuard tunnel terminated by Xray",
        tokens: ["udp", ":51820"],
        icon: Server,
        defaults: {
            protocol: "wireguard",
            port: 51820,
            listen: "0.0.0.0",
            network: "tcp",
            security: "none",
            wireguard_settings: { secretKey: "", mtu: 1420, endpoint: [], peers: [] },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "hysteria2",
        name: "Hysteria2",
        description: "QUIC-based protocol with built-in TLS (Xray-examples Hysteria2)",
        tokens: ["quic", "tls"],
        icon: Zap,
        defaults: {
            protocol: "hysteria2",
            port: 443,
            listen: "0.0.0.0",
            network: "",
            security: "tls",
            tls_settings: { serverName: "" },
            hysteria_settings: {},
            sniffing_settings: SNIFFING,
        },
    },

    // ---- Added from XTLS/Xray-examples ----
    {
        id: "vless-tcp-reality-vision",
        name: "VLESS + TCP + Reality + Vision",
        description: "The standard Xray setup: raw TCP, Reality, XTLS Vision flow (Xray-examples VLESS-TCP-XTLS-Vision-REALITY)",
        tokens: ["tcp", "reality", "vision"],
        icon: Shield,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "tcp",
            security: "reality",
            vless_settings: { flow: "xtls-rprx-vision" },
            reality_settings: REALITY_DEFAULTS,
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-tcp-tls-vision",
        name: "VLESS + TCP + TLS + Vision",
        description: "Raw TCP with your own certificate and XTLS Vision flow (Xray-examples VLESS-TCP-XTLS-Vision)",
        tokens: ["tcp", "tls", "vision"],
        icon: Shield,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "tcp",
            security: "tls",
            vless_settings: { flow: "xtls-rprx-vision" },
            tls_settings: { alpn: ["h2", "http/1.1"] },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-tcp-tls",
        name: "VLESS + TCP + TLS",
        description: "Raw TCP with TLS, no flow (Xray-examples VLESS-TCP-TLS)",
        tokens: ["tcp", "tls"],
        icon: Lock,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "tcp",
            security: "tls",
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-tcp-tls-fallbacks",
        name: "VLESS + TCP + TLS + Fallbacks",
        description: "Vision on 443 with fallbacks to a local web server on 80 and h2 on 8080 (Xray-examples All-in-One-fallbacks-Nginx)",
        tokens: ["tcp", "tls", "vision", "fallbacks"],
        icon: Waypoints,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "tcp",
            security: "tls",
            vless_settings: {
                flow: "xtls-rprx-vision",
                fallbacks: [
                    { dest: 80, xver: 0 },
                    { alpn: "h2", dest: 8080, xver: 0 },
                ],
            },
            tls_settings: { alpn: ["h2", "http/1.1"] },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-tcp",
        name: "VLESS + TCP",
        description: "Plain VLESS over TCP. Only for a trusted network, a tunnel, or behind a TLS-terminating proxy (Xray-examples VLESS-TCP)",
        tokens: ["tcp", "none"],
        icon: Network,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "tcp",
            security: "none",
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-ws-tls",
        name: "VLESS + WS + TLS",
        description: "WebSocket with TLS; CDN-friendly (Xray-examples VLESS-WSS-Nginx)",
        tokens: ["ws", "tls"],
        icon: Globe,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "ws",
            security: "tls",
            transport_settings: { path: "/" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-grpc-tls",
        name: "VLESS + gRPC + TLS",
        description: "gRPC transport with TLS (Xray-examples VLESS-GRPC)",
        tokens: ["grpc", "tls"],
        icon: Radio,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "grpc",
            security: "tls",
            transport_settings: { serviceName: "grpc" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-grpc-reality",
        name: "VLESS + gRPC + Reality",
        description: "gRPC transport with Reality (Xray-examples VLESS-gRPC-REALITY)",
        tokens: ["grpc", "reality"],
        icon: Shield,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "grpc",
            security: "reality",
            transport_settings: { serviceName: "grpc" },
            reality_settings: REALITY_DEFAULTS,
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-xhttp-tls-h3",
        name: "VLESS + XHTTP + TLS · H3",
        description: "XHTTP over HTTP/3 (QUIC) with TLS (Xray-examples VLESS-TLS-SplitHTTP-H3)",
        tokens: ["xhttp", "tls", "h3"],
        icon: Zap,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "xhttp",
            security: "tls",
            transport_settings: { path: "/", mode: "auto" },
            tls_settings: { alpn: ["h3"] },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-httpupgrade-tls",
        name: "VLESS + HTTPUpgrade + TLS",
        description: "Lighter WebSocket alternative; CDN-friendly (xtls.github.io transports/httpupgrade)",
        tokens: ["httpupgrade", "tls"],
        icon: Globe,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "httpupgrade",
            security: "tls",
            transport_settings: { path: "/" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vless-mkcp",
        name: "VLESS + mKCP",
        description: "UDP-based mKCP transport; no TLS (Xray-examples VLESS-mKCPSeed)",
        tokens: ["kcp", "none"],
        icon: Radio,
        defaults: {
            protocol: "vless",
            port: 443,
            listen: "0.0.0.0",
            network: "kcp",
            security: "none",
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vmess-tcp-tls",
        name: "VMess + TCP + TLS",
        description: "VMess over raw TCP with TLS (Xray-examples VMess-TCP-TLS)",
        tokens: ["tcp", "tls"],
        icon: Lock,
        defaults: {
            protocol: "vmess",
            port: 443,
            listen: "0.0.0.0",
            network: "tcp",
            security: "tls",
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vmess-tcp",
        name: "VMess + TCP",
        description: "Plain VMess over TCP; VMess has its own encryption (Xray-examples VMess-TCP)",
        tokens: ["tcp", "none"],
        icon: Network,
        defaults: {
            protocol: "vmess",
            port: 443,
            listen: "0.0.0.0",
            network: "tcp",
            security: "none",
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vmess-ws",
        name: "VMess + WS · behind CDN",
        description: "Plain WebSocket on localhost; a reverse proxy or CDN terminates TLS (Xray-examples VMess-Websocket)",
        tokens: ["ws", "none", "127.0.0.1"],
        icon: Globe,
        defaults: {
            protocol: "vmess",
            port: 8080,
            listen: "127.0.0.1",
            network: "ws",
            security: "none",
            transport_settings: { path: "/" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "vmess-mkcp",
        name: "VMess + mKCP",
        description: "VMess over UDP-based mKCP (Xray-examples VMess-mKCPSeed)",
        tokens: ["kcp", "none"],
        icon: Radio,
        defaults: {
            protocol: "vmess",
            port: 443,
            listen: "0.0.0.0",
            network: "kcp",
            security: "none",
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "trojan-tcp-tls",
        name: "Trojan + TCP + TLS",
        description: "Trojan over raw TCP with TLS (Xray-examples Trojan-TCP-TLS)",
        tokens: ["tcp", "tls"],
        icon: Eye,
        defaults: {
            protocol: "trojan",
            port: 443,
            listen: "0.0.0.0",
            network: "tcp",
            security: "tls",
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "trojan-grpc-tls",
        name: "Trojan + gRPC + TLS",
        description: "Trojan over gRPC with TLS (Xray-examples Trojan-gRPC-Caddy2/Nginx)",
        tokens: ["grpc", "tls"],
        icon: Radio,
        defaults: {
            protocol: "trojan",
            port: 443,
            listen: "0.0.0.0",
            network: "grpc",
            security: "tls",
            transport_settings: { serviceName: "grpc" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "shadowsocks-aead",
        name: "Shadowsocks AEAD",
        description: "Classic Shadowsocks with AES-256-GCM (Xray-examples Shadowsocks-AEAD)",
        tokens: ["tcp", "aes-256-gcm"],
        icon: Wifi,
        defaults: {
            protocol: "shadowsocks",
            port: 8388,
            listen: "0.0.0.0",
            network: "tcp",
            security: "none",
            shadowsocks_settings: { method: "aes-256-gcm", network: "tcp,udp" },
            sniffing_settings: SNIFFING,
        },
    },
    {
        id: "socks5-tls",
        name: "SOCKS5 + TLS",
        description: "Password-authenticated SOCKS5 wrapped in TLS (Xray-examples Socks5-TLS)",
        tokens: ["tcp", "tls", "auth"],
        icon: Lock,
        defaults: {
            protocol: "socks",
            port: 1080,
            listen: "0.0.0.0",
            network: "tcp",
            security: "tls",
            socks_settings: { auth: "password", udp: false, accounts: [] },
            sniffing_settings: SNIFFING,
        },
    },
]
