// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v7.34.1
// source: node_agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeAgent_GetStatus_FullMethodName                   = "/nodeagent.NodeAgent/GetStatus"
	NodeAgent_StartXray_FullMethodName                   = "/nodeagent.NodeAgent/StartXray"
	NodeAgent_StopXray_FullMethodName                    = "/nodeagent.NodeAgent/StopXray"
	NodeAgent_RestartXray_FullMethodName                 = "/nodeagent.NodeAgent/RestartXray"
	NodeAgent_PushConfig_FullMethodName                  = "/nodeagent.NodeAgent/PushConfig"
	NodeAgent_UpdateXrayAPIConfig_FullMethodName         = "/nodeagent.NodeAgent/UpdateXrayAPIConfig"
	NodeAgent_GetCurrentConfig_FullMethodName            = "/nodeagent.NodeAgent/GetCurrentConfig"
	NodeAgent_ValidateConfig_FullMethodName              = "/nodeagent.NodeAgent/ValidateConfig"
	NodeAgent_AddUser_FullMethodName                     = "/nodeagent.NodeAgent/AddUser"
	NodeAgent_RemoveUser_FullMethodName                  = "/nodeagent.NodeAgent/RemoveUser"
	NodeAgent_ListUsers_FullMethodName                   = "/nodeagent.NodeAgent/ListUsers"
	NodeAgent_GetSystemStats_FullMethodName              = "/nodeagent.NodeAgent/GetSystemStats"
	NodeAgent_GetHostInfo_FullMethodName                 = "/nodeagent.NodeAgent/GetHostInfo"
	NodeAgent_GetXrayStats_FullMethodName                = "/nodeagent.NodeAgent/GetXrayStats"
	NodeAgent_StreamLogs_FullMethodName                  = "/nodeagent.NodeAgent/StreamLogs"
	NodeAgent_HealthCheck_FullMethodName                 = "/nodeagent.NodeAgent/HealthCheck"
	NodeAgent_GetVersion_FullMethodName                  = "/nodeagent.NodeAgent/GetVersion"
	NodeAgent_Heartbeat_FullMethodName                   = "/nodeagent.NodeAgent/Heartbeat"
	NodeAgent_SelfUpdate_FullMethodName                  = "/nodeagent.NodeAgent/SelfUpdate"
	NodeAgent_GetSelfChecksum_FullMethodName             = "/nodeagent.NodeAgent/GetSelfChecksum"
	NodeAgent_UpdateXrayBinary_FullMethodName            = "/nodeagent.NodeAgent/UpdateXrayBinary"
	NodeAgent_Uninstall_FullMethodName                   = "/nodeagent.NodeAgent/Uninstall"
	NodeAgent_Wipe_FullMethodName                        = "/nodeagent.NodeAgent/Wipe"
	NodeAgent_Nuke_FullMethodName                        = "/nodeagent.NodeAgent/Nuke"
	NodeAgent_GetSSHStatus_FullMethodName                = "/nodeagent.NodeAgent/GetSSHStatus"
	NodeAgent_UpdateSSHConfig_FullMethodName             = "/nodeagent.NodeAgent/UpdateSSHConfig"
	NodeAgent_ClearSSHLogs_FullMethodName                = "/nodeagent.NodeAgent/ClearSSHLogs"
	NodeAgent_RestartSSH_FullMethodName                  = "/nodeagent.NodeAgent/RestartSSH"
	NodeAgent_OpenTerminal_FullMethodName                = "/nodeagent.NodeAgent/OpenTerminal"
	NodeAgent_UpdateCertDenylist_FullMethodName          = "/nodeagent.NodeAgent/UpdateCertDenylist"
	NodeAgent_WriteFile_FullMethodName                   = "/nodeagent.NodeAgent/WriteFile"
	NodeAgent_TestOutbound_FullMethodName                = "/nodeagent.NodeAgent/TestOutbound"
	NodeAgent_GetUserOnlineIPs_FullMethodName            = "/nodeagent.NodeAgent/GetUserOnlineIPs"
	NodeAgent_GetAllUsersOnlineIPs_FullMethodName        = "/nodeagent.NodeAgent/GetAllUsersOnlineIPs"
	NodeAgent_GenerateVLESSKeys_FullMethodName           = "/nodeagent.NodeAgent/GenerateVLESSKeys"
	NodeAgent_SetupBandwidth_FullMethodName              = "/nodeagent.NodeAgent/SetupBandwidth"
	NodeAgent_TeardownBandwidth_FullMethodName           = "/nodeagent.NodeAgent/TeardownBandwidth"
	NodeAgent_GetBufferedTraffic_FullMethodName          = "/nodeagent.NodeAgent/GetBufferedTraffic"
	NodeAgent_AckBufferedTraffic_FullMethodName          = "/nodeagent.NodeAgent/AckBufferedTraffic"
	NodeAgent_GetAccessLogs_FullMethodName               = "/nodeagent.NodeAgent/GetAccessLogs"
	NodeAgent_GetBufferedAccessLogSummary_FullMethodName = "/nodeagent.NodeAgent/GetBufferedAccessLogSummary"
	NodeAgent_AckBufferedAccessLogSummary_FullMethodName = "/nodeagent.NodeAgent/AckBufferedAccessLogSummary"
	NodeAgent_GetStarlinkStatus_FullMethodName           = "/nodeagent.NodeAgent/GetStarlinkStatus"
	NodeAgent_GetStarlinkObstructionMap_FullMethodName   = "/nodeagent.NodeAgent/GetStarlinkObstructionMap"
	NodeAgent_ExecuteCommand_FullMethodName              = "/nodeagent.NodeAgent/ExecuteCommand"
)

// NodeAgentClient is the client API for NodeAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeAgent service provides remote management capabilities for xray-core nodes
type NodeAgentClient interface {
	// GetStatus returns the current status of the node agent and xray process
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error)
	// StartXray starts the xray-core process
	StartXray(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandResponse, error)
	// StopXray gracefully stops the xray-core process
	StopXray(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// RestartXray restarts the xray-core process (stop + start)
	RestartXray(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// PushConfig receives a full xray config.json and writes it to disk
	PushConfig(ctx context.Context, in *ConfigPayload, opts ...grpc.CallOption) (*CommandResponse, error)
	// UpdateXrayAPIConfig updates the Xray API address in the agent config
	UpdateXrayAPIConfig(ctx context.Context, in *XrayAPIConfigPayload, opts ...grpc.CallOption) (*CommandResponse, error)
	// GetCurrentConfig returns the current config.json contents
	GetCurrentConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigPayload, error)
	// ValidateConfig validates a config without applying it
	ValidateConfig(ctx context.Context, in *ConfigPayload, opts ...grpc.CallOption) (*ValidationResult, error)
	// AddUser adds a user to an inbound handler
	AddUser(ctx context.Context, in *UserPayload, opts ...grpc.CallOption) (*CommandResponse, error)
	// RemoveUser removes a user from an inbound handler
	RemoveUser(ctx context.Context, in *UserPayload, opts ...grpc.CallOption) (*CommandResponse, error)
	// ListUsers returns all users on a specific inbound
	ListUsers(ctx context.Context, in *InboundSelector, opts ...grpc.CallOption) (*UserList, error)
	// GetSystemStats returns CPU, memory, disk, and network statistics
	GetSystemStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemStats, error)
	// GetHostInfo returns static host information (OS, CPU, etc.)
	GetHostInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HostInfo, error)
	// GetXrayStats returns xray traffic statistics
	GetXrayStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*XrayStats, error)
	// StreamLogs streams xray access/error logs in real-time
	StreamLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error)
	// HealthCheck performs a health check on the agent and xray
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	// GetVersion returns agent and xray version information
	GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionInfo, error)
	// Heartbeat maintains a bidirectional heartbeat stream for connection monitoring
	Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatPing, HeartbeatPong], error)
	// SelfUpdate receives a new agent binary and updates in-place
	SelfUpdate(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// GetSelfChecksum returns the SHA256 checksum of the running binary
	GetSelfChecksum(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChecksumResponse, error)
	// UpdateXrayBinary downloads and installs a specific xray-core version
	UpdateXrayBinary(ctx context.Context, in *UpdateXrayRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// Uninstall removes the agent and xray from the system (Destructive)
	Uninstall(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandResponse, error)
	// Wipe removes our footprint from the node and (optionally when mode=NUKE)
	// performs scorched-earth destruction. Unary — returns once everything is
	// done, just before the agent self-destructs.
	Wipe(ctx context.Context, in *NukeRequest, opts ...grpc.CallOption) (*NukeReport, error)
	// Nuke is the streaming variant: one NukePhaseResult per phase as they run,
	// then a terminal NukeReport, then the stream closes as the agent exits.
	// Reverse-mode agents return Unimplemented — callers should fall back to Wipe.
	Nuke(ctx context.Context, in *NukeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NukeProgress], error)
	// GetSSHStatus returns the current status of the SSH service
	GetSSHStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SSHStatus, error)
	// UpdateSSHConfig updates the SSH configuration (port, enabled)
	UpdateSSHConfig(ctx context.Context, in *SSHConfigPayload, opts ...grpc.CallOption) (*CommandResponse, error)
	// ClearSSHLogs clears/truncates the SSH auth logs
	ClearSSHLogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandResponse, error)
	// RestartSSH restarts the SSH service
	RestartSSH(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandResponse, error)
	// OpenTerminal starts an interactive PTY shell session (bidirectional stream)
	OpenTerminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalInput, TerminalOutput], error)
	// UpdateCertDenylist pushes a list of revoked certificate serial numbers
	UpdateCertDenylist(ctx context.Context, in *CertDenylist, opts ...grpc.CallOption) (*CommandResponse, error)
	// WriteFile writes content to a file on the node
	WriteFile(ctx context.Context, in *FilePayload, opts ...grpc.CallOption) (*CommandResponse, error)
	// TestOutbound tests outbound connectivity via xray-knife
	TestOutbound(ctx context.Context, in *OutboundTestRequest, opts ...grpc.CallOption) (*OutboundTestResponse, error)
	// GetUserOnlineIPs returns the IPs currently connected for a specific user
	GetUserOnlineIPs(ctx context.Context, in *UserEmailRequest, opts ...grpc.CallOption) (*OnlineIPsResponse, error)
	// GetAllUsersOnlineIPs returns, in one call, the IP→timestamp map for
	// every currently-online user. Used by the scheduler's stats sweep to
	// collapse the N+1 GetUserOnlineIPs round-trips into a single RPC —
	// the agent still hits Xray's stats API once per user locally, but
	// the expensive hub↔agent latency is paid once.
	GetAllUsersOnlineIPs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllOnlineIPsResponse, error)
	// GenerateVLESSKeys runs xray vlessenc to generate VLESS encryption keys (X25519 + ML-KEM-768)
	GenerateVLESSKeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VLESSKeysResponse, error)
	// SetupBandwidth initializes TC bandwidth shaping on the node
	SetupBandwidth(ctx context.Context, in *BandwidthRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// TeardownBandwidth removes TC bandwidth shaping from the node
	TeardownBandwidth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandResponse, error)
	// GetBufferedTraffic returns time-bucketed traffic records from the agent's local buffer
	GetBufferedTraffic(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BufferedTrafficStats, error)
	// AckBufferedTraffic acknowledges receipt of traffic records up to a given timestamp
	AckBufferedTraffic(ctx context.Context, in *AckTrafficRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// GetAccessLogs returns recent parsed access log entries, optionally filtered by email
	GetAccessLogs(ctx context.Context, in *AccessLogRequest, opts ...grpc.CallOption) (*AccessLogResponse, error)
	// GetBufferedAccessLogSummary returns hourly aggregated access log summaries
	GetBufferedAccessLogSummary(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BufferedAccessLogSummary, error)
	// AckBufferedAccessLogSummary acknowledges processing of summaries up to a timestamp
	AckBufferedAccessLogSummary(ctx context.Context, in *AckAccessLogSummaryRequest, opts ...grpc.CallOption) (*CommandResponse, error)
	// GetStarlinkStatus queries the local Starlink dish for real-time status
	GetStarlinkStatus(ctx context.Context, in *StarlinkRequest, opts ...grpc.CallOption) (*StarlinkStatusResponse, error)
	// GetStarlinkObstructionMap queries the local Starlink dish for its obstruction map
	GetStarlinkObstructionMap(ctx context.Context, in *StarlinkRequest, opts ...grpc.CallOption) (*StarlinkObstructionMapResponse, error)
	// ExecuteCommand runs a shell command on the node and returns the result
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
}

type nodeAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeAgentClient(cc grpc.ClientConnInterface) NodeAgentClient {
	return &nodeAgentClient{cc}
}

func (c *nodeAgentClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*NodeStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatus)
	err := c.cc.Invoke(ctx, NodeAgent_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) StartXray(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_StartXray_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) StopXray(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_StopXray_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) RestartXray(ctx context.Context, in *RestartRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_RestartXray_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) PushConfig(ctx context.Context, in *ConfigPayload, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_PushConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) UpdateXrayAPIConfig(ctx context.Context, in *XrayAPIConfigPayload, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_UpdateXrayAPIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetCurrentConfig(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ConfigPayload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigPayload)
	err := c.cc.Invoke(ctx, NodeAgent_GetCurrentConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ValidateConfig(ctx context.Context, in *ConfigPayload, opts ...grpc.CallOption) (*ValidationResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidationResult)
	err := c.cc.Invoke(ctx, NodeAgent_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) AddUser(ctx context.Context, in *UserPayload, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_AddUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) RemoveUser(ctx context.Context, in *UserPayload, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_RemoveUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ListUsers(ctx context.Context, in *InboundSelector, opts ...grpc.CallOption) (*UserList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserList)
	err := c.cc.Invoke(ctx, NodeAgent_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetSystemStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStats)
	err := c.cc.Invoke(ctx, NodeAgent_GetSystemStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetHostInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HostInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostInfo)
	err := c.cc.Invoke(ctx, NodeAgent_GetHostInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetXrayStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*XrayStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(XrayStats)
	err := c.cc.Invoke(ctx, NodeAgent_GetXrayStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) StreamLogs(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[0], NodeAgent_StreamLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogRequest, LogEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_StreamLogsClient = grpc.ServerStreamingClient[LogEntry]

func (c *nodeAgentClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, NodeAgent_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionInfo)
	err := c.cc.Invoke(ctx, NodeAgent_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Heartbeat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HeartbeatPing, HeartbeatPong], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[1], NodeAgent_Heartbeat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HeartbeatPing, HeartbeatPong]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_HeartbeatClient = grpc.BidiStreamingClient[HeartbeatPing, HeartbeatPong]

func (c *nodeAgentClient) SelfUpdate(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, NodeAgent_SelfUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetSelfChecksum(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ChecksumResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChecksumResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetSelfChecksum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) UpdateXrayBinary(ctx context.Context, in *UpdateXrayRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_UpdateXrayBinary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Uninstall(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_Uninstall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Wipe(ctx context.Context, in *NukeRequest, opts ...grpc.CallOption) (*NukeReport, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NukeReport)
	err := c.cc.Invoke(ctx, NodeAgent_Wipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) Nuke(ctx context.Context, in *NukeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NukeProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[2], NodeAgent_Nuke_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NukeRequest, NukeProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_NukeClient = grpc.ServerStreamingClient[NukeProgress]

func (c *nodeAgentClient) GetSSHStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SSHStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSHStatus)
	err := c.cc.Invoke(ctx, NodeAgent_GetSSHStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) UpdateSSHConfig(ctx context.Context, in *SSHConfigPayload, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_UpdateSSHConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ClearSSHLogs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ClearSSHLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) RestartSSH(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_RestartSSH_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) OpenTerminal(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TerminalInput, TerminalOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeAgent_ServiceDesc.Streams[3], NodeAgent_OpenTerminal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TerminalInput, TerminalOutput]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_OpenTerminalClient = grpc.BidiStreamingClient[TerminalInput, TerminalOutput]

func (c *nodeAgentClient) UpdateCertDenylist(ctx context.Context, in *CertDenylist, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_UpdateCertDenylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) WriteFile(ctx context.Context, in *FilePayload, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_WriteFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) TestOutbound(ctx context.Context, in *OutboundTestRequest, opts ...grpc.CallOption) (*OutboundTestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OutboundTestResponse)
	err := c.cc.Invoke(ctx, NodeAgent_TestOutbound_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetUserOnlineIPs(ctx context.Context, in *UserEmailRequest, opts ...grpc.CallOption) (*OnlineIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OnlineIPsResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetUserOnlineIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetAllUsersOnlineIPs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*AllOnlineIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllOnlineIPsResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetAllUsersOnlineIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GenerateVLESSKeys(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VLESSKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VLESSKeysResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GenerateVLESSKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) SetupBandwidth(ctx context.Context, in *BandwidthRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_SetupBandwidth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) TeardownBandwidth(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_TeardownBandwidth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetBufferedTraffic(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BufferedTrafficStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BufferedTrafficStats)
	err := c.cc.Invoke(ctx, NodeAgent_GetBufferedTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) AckBufferedTraffic(ctx context.Context, in *AckTrafficRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_AckBufferedTraffic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetAccessLogs(ctx context.Context, in *AccessLogRequest, opts ...grpc.CallOption) (*AccessLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccessLogResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetAccessLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetBufferedAccessLogSummary(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BufferedAccessLogSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BufferedAccessLogSummary)
	err := c.cc.Invoke(ctx, NodeAgent_GetBufferedAccessLogSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) AckBufferedAccessLogSummary(ctx context.Context, in *AckAccessLogSummaryRequest, opts ...grpc.CallOption) (*CommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_AckBufferedAccessLogSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetStarlinkStatus(ctx context.Context, in *StarlinkRequest, opts ...grpc.CallOption) (*StarlinkStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarlinkStatusResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetStarlinkStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) GetStarlinkObstructionMap(ctx context.Context, in *StarlinkRequest, opts ...grpc.CallOption) (*StarlinkObstructionMapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StarlinkObstructionMapResponse)
	err := c.cc.Invoke(ctx, NodeAgent_GetStarlinkObstructionMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeAgentClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, NodeAgent_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeAgentServer is the server API for NodeAgent service.
// All implementations must embed UnimplementedNodeAgentServer
// for forward compatibility.
//
// NodeAgent service provides remote management capabilities for xray-core nodes
type NodeAgentServer interface {
	// GetStatus returns the current status of the node agent and xray process
	GetStatus(context.Context, *Empty) (*NodeStatus, error)
	// StartXray starts the xray-core process
	StartXray(context.Context, *Empty) (*CommandResponse, error)
	// StopXray gracefully stops the xray-core process
	StopXray(context.Context, *StopRequest) (*CommandResponse, error)
	// RestartXray restarts the xray-core process (stop + start)
	RestartXray(context.Context, *RestartRequest) (*CommandResponse, error)
	// PushConfig receives a full xray config.json and writes it to disk
	PushConfig(context.Context, *ConfigPayload) (*CommandResponse, error)
	// UpdateXrayAPIConfig updates the Xray API address in the agent config
	UpdateXrayAPIConfig(context.Context, *XrayAPIConfigPayload) (*CommandResponse, error)
	// GetCurrentConfig returns the current config.json contents
	GetCurrentConfig(context.Context, *Empty) (*ConfigPayload, error)
	// ValidateConfig validates a config without applying it
	ValidateConfig(context.Context, *ConfigPayload) (*ValidationResult, error)
	// AddUser adds a user to an inbound handler
	AddUser(context.Context, *UserPayload) (*CommandResponse, error)
	// RemoveUser removes a user from an inbound handler
	RemoveUser(context.Context, *UserPayload) (*CommandResponse, error)
	// ListUsers returns all users on a specific inbound
	ListUsers(context.Context, *InboundSelector) (*UserList, error)
	// GetSystemStats returns CPU, memory, disk, and network statistics
	GetSystemStats(context.Context, *Empty) (*SystemStats, error)
	// GetHostInfo returns static host information (OS, CPU, etc.)
	GetHostInfo(context.Context, *Empty) (*HostInfo, error)
	// GetXrayStats returns xray traffic statistics
	GetXrayStats(context.Context, *StatsRequest) (*XrayStats, error)
	// StreamLogs streams xray access/error logs in real-time
	StreamLogs(*LogRequest, grpc.ServerStreamingServer[LogEntry]) error
	// HealthCheck performs a health check on the agent and xray
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	// GetVersion returns agent and xray version information
	GetVersion(context.Context, *Empty) (*VersionInfo, error)
	// Heartbeat maintains a bidirectional heartbeat stream for connection monitoring
	Heartbeat(grpc.BidiStreamingServer[HeartbeatPing, HeartbeatPong]) error
	// SelfUpdate receives a new agent binary and updates in-place
	SelfUpdate(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// GetSelfChecksum returns the SHA256 checksum of the running binary
	GetSelfChecksum(context.Context, *Empty) (*ChecksumResponse, error)
	// UpdateXrayBinary downloads and installs a specific xray-core version
	UpdateXrayBinary(context.Context, *UpdateXrayRequest) (*CommandResponse, error)
	// Uninstall removes the agent and xray from the system (Destructive)
	Uninstall(context.Context, *Empty) (*CommandResponse, error)
	// Wipe removes our footprint from the node and (optionally when mode=NUKE)
	// performs scorched-earth destruction. Unary — returns once everything is
	// done, just before the agent self-destructs.
	Wipe(context.Context, *NukeRequest) (*NukeReport, error)
	// Nuke is the streaming variant: one NukePhaseResult per phase as they run,
	// then a terminal NukeReport, then the stream closes as the agent exits.
	// Reverse-mode agents return Unimplemented — callers should fall back to Wipe.
	Nuke(*NukeRequest, grpc.ServerStreamingServer[NukeProgress]) error
	// GetSSHStatus returns the current status of the SSH service
	GetSSHStatus(context.Context, *Empty) (*SSHStatus, error)
	// UpdateSSHConfig updates the SSH configuration (port, enabled)
	UpdateSSHConfig(context.Context, *SSHConfigPayload) (*CommandResponse, error)
	// ClearSSHLogs clears/truncates the SSH auth logs
	ClearSSHLogs(context.Context, *Empty) (*CommandResponse, error)
	// RestartSSH restarts the SSH service
	RestartSSH(context.Context, *Empty) (*CommandResponse, error)
	// OpenTerminal starts an interactive PTY shell session (bidirectional stream)
	OpenTerminal(grpc.BidiStreamingServer[TerminalInput, TerminalOutput]) error
	// UpdateCertDenylist pushes a list of revoked certificate serial numbers
	UpdateCertDenylist(context.Context, *CertDenylist) (*CommandResponse, error)
	// WriteFile writes content to a file on the node
	WriteFile(context.Context, *FilePayload) (*CommandResponse, error)
	// TestOutbound tests outbound connectivity via xray-knife
	TestOutbound(context.Context, *OutboundTestRequest) (*OutboundTestResponse, error)
	// GetUserOnlineIPs returns the IPs currently connected for a specific user
	GetUserOnlineIPs(context.Context, *UserEmailRequest) (*OnlineIPsResponse, error)
	// GetAllUsersOnlineIPs returns, in one call, the IP→timestamp map for
	// every currently-online user. Used by the scheduler's stats sweep to
	// collapse the N+1 GetUserOnlineIPs round-trips into a single RPC —
	// the agent still hits Xray's stats API once per user locally, but
	// the expensive hub↔agent latency is paid once.
	GetAllUsersOnlineIPs(context.Context, *Empty) (*AllOnlineIPsResponse, error)
	// GenerateVLESSKeys runs xray vlessenc to generate VLESS encryption keys (X25519 + ML-KEM-768)
	GenerateVLESSKeys(context.Context, *Empty) (*VLESSKeysResponse, error)
	// SetupBandwidth initializes TC bandwidth shaping on the node
	SetupBandwidth(context.Context, *BandwidthRequest) (*CommandResponse, error)
	// TeardownBandwidth removes TC bandwidth shaping from the node
	TeardownBandwidth(context.Context, *Empty) (*CommandResponse, error)
	// GetBufferedTraffic returns time-bucketed traffic records from the agent's local buffer
	GetBufferedTraffic(context.Context, *Empty) (*BufferedTrafficStats, error)
	// AckBufferedTraffic acknowledges receipt of traffic records up to a given timestamp
	AckBufferedTraffic(context.Context, *AckTrafficRequest) (*CommandResponse, error)
	// GetAccessLogs returns recent parsed access log entries, optionally filtered by email
	GetAccessLogs(context.Context, *AccessLogRequest) (*AccessLogResponse, error)
	// GetBufferedAccessLogSummary returns hourly aggregated access log summaries
	GetBufferedAccessLogSummary(context.Context, *Empty) (*BufferedAccessLogSummary, error)
	// AckBufferedAccessLogSummary acknowledges processing of summaries up to a timestamp
	AckBufferedAccessLogSummary(context.Context, *AckAccessLogSummaryRequest) (*CommandResponse, error)
	// GetStarlinkStatus queries the local Starlink dish for real-time status
	GetStarlinkStatus(context.Context, *StarlinkRequest) (*StarlinkStatusResponse, error)
	// GetStarlinkObstructionMap queries the local Starlink dish for its obstruction map
	GetStarlinkObstructionMap(context.Context, *StarlinkRequest) (*StarlinkObstructionMapResponse, error)
	// ExecuteCommand runs a shell command on the node and returns the result
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	mustEmbedUnimplementedNodeAgentServer()
}

// UnimplementedNodeAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeAgentServer struct{}

func (UnimplementedNodeAgentServer) GetStatus(context.Context, *Empty) (*NodeStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedNodeAgentServer) StartXray(context.Context, *Empty) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartXray not implemented")
}
func (UnimplementedNodeAgentServer) StopXray(context.Context, *StopRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopXray not implemented")
}
func (UnimplementedNodeAgentServer) RestartXray(context.Context, *RestartRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartXray not implemented")
}
func (UnimplementedNodeAgentServer) PushConfig(context.Context, *ConfigPayload) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushConfig not implemented")
}
func (UnimplementedNodeAgentServer) UpdateXrayAPIConfig(context.Context, *XrayAPIConfigPayload) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateXrayAPIConfig not implemented")
}
func (UnimplementedNodeAgentServer) GetCurrentConfig(context.Context, *Empty) (*ConfigPayload, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCurrentConfig not implemented")
}
func (UnimplementedNodeAgentServer) ValidateConfig(context.Context, *ConfigPayload) (*ValidationResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedNodeAgentServer) AddUser(context.Context, *UserPayload) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUser not implemented")
}
func (UnimplementedNodeAgentServer) RemoveUser(context.Context, *UserPayload) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUser not implemented")
}
func (UnimplementedNodeAgentServer) ListUsers(context.Context, *InboundSelector) (*UserList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsers not implemented")
}
func (UnimplementedNodeAgentServer) GetSystemStats(context.Context, *Empty) (*SystemStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemStats not implemented")
}
func (UnimplementedNodeAgentServer) GetHostInfo(context.Context, *Empty) (*HostInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHostInfo not implemented")
}
func (UnimplementedNodeAgentServer) GetXrayStats(context.Context, *StatsRequest) (*XrayStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetXrayStats not implemented")
}
func (UnimplementedNodeAgentServer) StreamLogs(*LogRequest, grpc.ServerStreamingServer[LogEntry]) error {
	return status.Error(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedNodeAgentServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNodeAgentServer) GetVersion(context.Context, *Empty) (*VersionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedNodeAgentServer) Heartbeat(grpc.BidiStreamingServer[HeartbeatPing, HeartbeatPong]) error {
	return status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedNodeAgentServer) SelfUpdate(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelfUpdate not implemented")
}
func (UnimplementedNodeAgentServer) GetSelfChecksum(context.Context, *Empty) (*ChecksumResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSelfChecksum not implemented")
}
func (UnimplementedNodeAgentServer) UpdateXrayBinary(context.Context, *UpdateXrayRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateXrayBinary not implemented")
}
func (UnimplementedNodeAgentServer) Uninstall(context.Context, *Empty) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Uninstall not implemented")
}
func (UnimplementedNodeAgentServer) Wipe(context.Context, *NukeRequest) (*NukeReport, error) {
	return nil, status.Error(codes.Unimplemented, "method Wipe not implemented")
}
func (UnimplementedNodeAgentServer) Nuke(*NukeRequest, grpc.ServerStreamingServer[NukeProgress]) error {
	return status.Error(codes.Unimplemented, "method Nuke not implemented")
}
func (UnimplementedNodeAgentServer) GetSSHStatus(context.Context, *Empty) (*SSHStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSSHStatus not implemented")
}
func (UnimplementedNodeAgentServer) UpdateSSHConfig(context.Context, *SSHConfigPayload) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSSHConfig not implemented")
}
func (UnimplementedNodeAgentServer) ClearSSHLogs(context.Context, *Empty) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearSSHLogs not implemented")
}
func (UnimplementedNodeAgentServer) RestartSSH(context.Context, *Empty) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestartSSH not implemented")
}
func (UnimplementedNodeAgentServer) OpenTerminal(grpc.BidiStreamingServer[TerminalInput, TerminalOutput]) error {
	return status.Error(codes.Unimplemented, "method OpenTerminal not implemented")
}
func (UnimplementedNodeAgentServer) UpdateCertDenylist(context.Context, *CertDenylist) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCertDenylist not implemented")
}
func (UnimplementedNodeAgentServer) WriteFile(context.Context, *FilePayload) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WriteFile not implemented")
}
func (UnimplementedNodeAgentServer) TestOutbound(context.Context, *OutboundTestRequest) (*OutboundTestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestOutbound not implemented")
}
func (UnimplementedNodeAgentServer) GetUserOnlineIPs(context.Context, *UserEmailRequest) (*OnlineIPsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserOnlineIPs not implemented")
}
func (UnimplementedNodeAgentServer) GetAllUsersOnlineIPs(context.Context, *Empty) (*AllOnlineIPsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllUsersOnlineIPs not implemented")
}
func (UnimplementedNodeAgentServer) GenerateVLESSKeys(context.Context, *Empty) (*VLESSKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateVLESSKeys not implemented")
}
func (UnimplementedNodeAgentServer) SetupBandwidth(context.Context, *BandwidthRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetupBandwidth not implemented")
}
func (UnimplementedNodeAgentServer) TeardownBandwidth(context.Context, *Empty) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TeardownBandwidth not implemented")
}
func (UnimplementedNodeAgentServer) GetBufferedTraffic(context.Context, *Empty) (*BufferedTrafficStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBufferedTraffic not implemented")
}
func (UnimplementedNodeAgentServer) AckBufferedTraffic(context.Context, *AckTrafficRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckBufferedTraffic not implemented")
}
func (UnimplementedNodeAgentServer) GetAccessLogs(context.Context, *AccessLogRequest) (*AccessLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccessLogs not implemented")
}
func (UnimplementedNodeAgentServer) GetBufferedAccessLogSummary(context.Context, *Empty) (*BufferedAccessLogSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBufferedAccessLogSummary not implemented")
}
func (UnimplementedNodeAgentServer) AckBufferedAccessLogSummary(context.Context, *AckAccessLogSummaryRequest) (*CommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckBufferedAccessLogSummary not implemented")
}
func (UnimplementedNodeAgentServer) GetStarlinkStatus(context.Context, *StarlinkRequest) (*StarlinkStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStarlinkStatus not implemented")
}
func (UnimplementedNodeAgentServer) GetStarlinkObstructionMap(context.Context, *StarlinkRequest) (*StarlinkObstructionMapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStarlinkObstructionMap not implemented")
}
func (UnimplementedNodeAgentServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedNodeAgentServer) mustEmbedUnimplementedNodeAgentServer() {}
func (UnimplementedNodeAgentServer) testEmbeddedByValue()                   {}

// UnsafeNodeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeAgentServer will
// result in compilation errors.
type UnsafeNodeAgentServer interface {
	mustEmbedUnimplementedNodeAgentServer()
}

func RegisterNodeAgentServer(s grpc.ServiceRegistrar, srv NodeAgentServer) {
	// If the following call panics, it indicates UnimplementedNodeAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeAgent_ServiceDesc, srv)
}

func _NodeAgent_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_StartXray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).StartXray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_StartXray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).StartXray(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_StopXray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).StopXray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_StopXray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).StopXray(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_RestartXray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).RestartXray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_RestartXray_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).RestartXray(ctx, req.(*RestartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_PushConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).PushConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_PushConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).PushConfig(ctx, req.(*ConfigPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_UpdateXrayAPIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(XrayAPIConfigPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).UpdateXrayAPIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_UpdateXrayAPIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).UpdateXrayAPIConfig(ctx, req.(*XrayAPIConfigPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetCurrentConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetCurrentConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetCurrentConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetCurrentConfig(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ValidateConfig(ctx, req.(*ConfigPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_AddUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).AddUser(ctx, req.(*UserPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_RemoveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).RemoveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_RemoveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).RemoveUser(ctx, req.(*UserPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InboundSelector)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ListUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ListUsers(ctx, req.(*InboundSelector))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetSystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetSystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetSystemStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetSystemStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetHostInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetHostInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetHostInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetHostInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetXrayStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetXrayStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetXrayStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetXrayStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).StreamLogs(m, &grpc.GenericServerStream[LogRequest, LogEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_StreamLogsServer = grpc.ServerStreamingServer[LogEntry]

func _NodeAgent_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Heartbeat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServer).Heartbeat(&grpc.GenericServerStream[HeartbeatPing, HeartbeatPong]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_HeartbeatServer = grpc.BidiStreamingServer[HeartbeatPing, HeartbeatPong]

func _NodeAgent_SelfUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).SelfUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_SelfUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).SelfUpdate(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetSelfChecksum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetSelfChecksum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetSelfChecksum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetSelfChecksum(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_UpdateXrayBinary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateXrayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).UpdateXrayBinary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_UpdateXrayBinary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).UpdateXrayBinary(ctx, req.(*UpdateXrayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Uninstall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).Uninstall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_Uninstall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).Uninstall(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Wipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NukeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).Wipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_Wipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).Wipe(ctx, req.(*NukeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_Nuke_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NukeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NodeAgentServer).Nuke(m, &grpc.GenericServerStream[NukeRequest, NukeProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_NukeServer = grpc.ServerStreamingServer[NukeProgress]

func _NodeAgent_GetSSHStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetSSHStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetSSHStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetSSHStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_UpdateSSHConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSHConfigPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).UpdateSSHConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_UpdateSSHConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).UpdateSSHConfig(ctx, req.(*SSHConfigPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ClearSSHLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ClearSSHLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ClearSSHLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ClearSSHLogs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_RestartSSH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).RestartSSH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_RestartSSH_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).RestartSSH(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_OpenTerminal_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeAgentServer).OpenTerminal(&grpc.GenericServerStream[TerminalInput, TerminalOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeAgent_OpenTerminalServer = grpc.BidiStreamingServer[TerminalInput, TerminalOutput]

func _NodeAgent_UpdateCertDenylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CertDenylist)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).UpdateCertDenylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_UpdateCertDenylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).UpdateCertDenylist(ctx, req.(*CertDenylist))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_WriteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilePayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).WriteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_WriteFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).WriteFile(ctx, req.(*FilePayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_TestOutbound_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutboundTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).TestOutbound(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_TestOutbound_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).TestOutbound(ctx, req.(*OutboundTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetUserOnlineIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetUserOnlineIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetUserOnlineIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetUserOnlineIPs(ctx, req.(*UserEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetAllUsersOnlineIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetAllUsersOnlineIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetAllUsersOnlineIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetAllUsersOnlineIPs(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GenerateVLESSKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GenerateVLESSKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GenerateVLESSKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GenerateVLESSKeys(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_SetupBandwidth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BandwidthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).SetupBandwidth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_SetupBandwidth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).SetupBandwidth(ctx, req.(*BandwidthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_TeardownBandwidth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).TeardownBandwidth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_TeardownBandwidth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).TeardownBandwidth(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetBufferedTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetBufferedTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetBufferedTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetBufferedTraffic(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_AckBufferedTraffic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckTrafficRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).AckBufferedTraffic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_AckBufferedTraffic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).AckBufferedTraffic(ctx, req.(*AckTrafficRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetAccessLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetAccessLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetAccessLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetAccessLogs(ctx, req.(*AccessLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetBufferedAccessLogSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetBufferedAccessLogSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetBufferedAccessLogSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetBufferedAccessLogSummary(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_AckBufferedAccessLogSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckAccessLogSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).AckBufferedAccessLogSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_AckBufferedAccessLogSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).AckBufferedAccessLogSummary(ctx, req.(*AckAccessLogSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetStarlinkStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetStarlinkStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetStarlinkStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetStarlinkStatus(ctx, req.(*StarlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_GetStarlinkObstructionMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StarlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).GetStarlinkObstructionMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_GetStarlinkObstructionMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).GetStarlinkObstructionMap(ctx, req.(*StarlinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeAgent_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeAgentServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeAgent_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeAgentServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeAgent_ServiceDesc is the grpc.ServiceDesc for NodeAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodeagent.NodeAgent",
	HandlerType: (*NodeAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _NodeAgent_GetStatus_Handler,
		},
		{
			MethodName: "StartXray",
			Handler:    _NodeAgent_StartXray_Handler,
		},
		{
			MethodName: "StopXray",
			Handler:    _NodeAgent_StopXray_Handler,
		},
		{
			MethodName: "RestartXray",
			Handler:    _NodeAgent_RestartXray_Handler,
		},
		{
			MethodName: "PushConfig",
			Handler:    _NodeAgent_PushConfig_Handler,
		},
		{
			MethodName: "UpdateXrayAPIConfig",
			Handler:    _NodeAgent_UpdateXrayAPIConfig_Handler,
		},
		{
			MethodName: "GetCurrentConfig",
			Handler:    _NodeAgent_GetCurrentConfig_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _NodeAgent_ValidateConfig_Handler,
		},
		{
			MethodName: "AddUser",
			Handler:    _NodeAgent_AddUser_Handler,
		},
		{
			MethodName: "RemoveUser",
			Handler:    _NodeAgent_RemoveUser_Handler,
		},
		{
			MethodName: "ListUsers",
			Handler:    _NodeAgent_ListUsers_Handler,
		},
		{
			MethodName: "GetSystemStats",
			Handler:    _NodeAgent_GetSystemStats_Handler,
		},
		{
			MethodName: "GetHostInfo",
			Handler:    _NodeAgent_GetHostInfo_Handler,
		},
		{
			MethodName: "GetXrayStats",
			Handler:    _NodeAgent_GetXrayStats_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NodeAgent_HealthCheck_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _NodeAgent_GetVersion_Handler,
		},
		{
			MethodName: "SelfUpdate",
			Handler:    _NodeAgent_SelfUpdate_Handler,
		},
		{
			MethodName: "GetSelfChecksum",
			Handler:    _NodeAgent_GetSelfChecksum_Handler,
		},
		{
			MethodName: "UpdateXrayBinary",
			Handler:    _NodeAgent_UpdateXrayBinary_Handler,
		},
		{
			MethodName: "Uninstall",
			Handler:    _NodeAgent_Uninstall_Handler,
		},
		{
			MethodName: "Wipe",
			Handler:    _NodeAgent_Wipe_Handler,
		},
		{
			MethodName: "GetSSHStatus",
			Handler:    _NodeAgent_GetSSHStatus_Handler,
		},
		{
			MethodName: "UpdateSSHConfig",
			Handler:    _NodeAgent_UpdateSSHConfig_Handler,
		},
		{
			MethodName: "ClearSSHLogs",
			Handler:    _NodeAgent_ClearSSHLogs_Handler,
		},
		{
			MethodName: "RestartSSH",
			Handler:    _NodeAgent_RestartSSH_Handler,
		},
		{
			MethodName: "UpdateCertDenylist",
			Handler:    _NodeAgent_UpdateCertDenylist_Handler,
		},
		{
			MethodName: "WriteFile",
			Handler:    _NodeAgent_WriteFile_Handler,
		},
		{
			MethodName: "TestOutbound",
			Handler:    _NodeAgent_TestOutbound_Handler,
		},
		{
			MethodName: "GetUserOnlineIPs",
			Handler:    _NodeAgent_GetUserOnlineIPs_Handler,
		},
		{
			MethodName: "GetAllUsersOnlineIPs",
			Handler:    _NodeAgent_GetAllUsersOnlineIPs_Handler,
		},
		{
			MethodName: "GenerateVLESSKeys",
			Handler:    _NodeAgent_GenerateVLESSKeys_Handler,
		},
		{
			MethodName: "SetupBandwidth",
			Handler:    _NodeAgent_SetupBandwidth_Handler,
		},
		{
			MethodName: "TeardownBandwidth",
			Handler:    _NodeAgent_TeardownBandwidth_Handler,
		},
		{
			MethodName: "GetBufferedTraffic",
			Handler:    _NodeAgent_GetBufferedTraffic_Handler,
		},
		{
			MethodName: "AckBufferedTraffic",
			Handler:    _NodeAgent_AckBufferedTraffic_Handler,
		},
		{
			MethodName: "GetAccessLogs",
			Handler:    _NodeAgent_GetAccessLogs_Handler,
		},
		{
			MethodName: "GetBufferedAccessLogSummary",
			Handler:    _NodeAgent_GetBufferedAccessLogSummary_Handler,
		},
		{
			MethodName: "AckBufferedAccessLogSummary",
			Handler:    _NodeAgent_AckBufferedAccessLogSummary_Handler,
		},
		{
			MethodName: "GetStarlinkStatus",
			Handler:    _NodeAgent_GetStarlinkStatus_Handler,
		},
		{
			MethodName: "GetStarlinkObstructionMap",
			Handler:    _NodeAgent_GetStarlinkObstructionMap_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _NodeAgent_ExecuteCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLogs",
			Handler:       _NodeAgent_StreamLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Heartbeat",
			Handler:       _NodeAgent_Heartbeat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Nuke",
			Handler:       _NodeAgent_Nuke_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "OpenTerminal",
			Handler:       _NodeAgent_OpenTerminal_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "node_agent.proto",
}
