package tool

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/joho/godotenv"
)

const (
	DefaultInstallDir       = "/usr/local/nasnet-panel"
	DefaultBackendService   = "nasnet-panel"
	DefaultContainerBackend = "nasnet_panel_backend"
	DefaultContainerDB      = "nasnet_panel_db"
	DefaultGithubRepo       = "nasnet-community/nasnet-panel-linux"
)

type Config struct {
	DeployMode        string
	DBDriver          string
	DBUser            string
	DBPassword        string
	DBName            string
	DBHost            string
	DBPort            string
	DBPath            string
	AppPort           string
	ProjectDir        string
	InstallDir        string
	BackupDir         string
	EnvFile           string
	ComposeFile       string
	SQLiteComposeFile string
	OfflineMode       bool
	GithubRepo        string
	GithubToken       string
}

func LoadConfig() (*Config, error) {
	scriptDir, err := os.Getwd()
	if err != nil {
		return nil, err
	}

	envFile := filepath.Join(scriptDir, ".env")
	if f := os.Getenv("ENV_FILE"); f != "" {
		envFile = f
	}

	_ = godotenv.Load(envFile)

	cfg := &Config{
		DeployMode:        getEnvDefault("DEPLOY_MODE", "docker"),
		DBDriver:          getEnvDefault("DB_DRIVER", "postgres"),
		DBUser:            getEnvDefault("DB_USER", "postgres"),
		DBPassword:        getEnvDefault("DB_PASSWORD", "postgres"),
		DBName:            getEnvDefault("DB_NAME", "nasnet_panel"),
		DBHost:            getEnvDefault("DB_HOST", "localhost"),
		DBPort:            getEnvDefault("DB_PORT", "5432"),
		DBPath:            getEnvDefault("DB_PATH", "/app/data/nasnet_panel.db"),
		AppPort:           getEnvDefault("APP_PORT", "9761"),
		ProjectDir:        scriptDir,
		InstallDir:        DefaultInstallDir,
		BackupDir:         filepath.Join(scriptDir, "data", "backups"),
		EnvFile:           envFile,
		ComposeFile:       filepath.Join(scriptDir, "docker-compose.yml"),
		SQLiteComposeFile: filepath.Join(scriptDir, "docker-compose.sqlite.yml"),
		OfflineMode:       os.Getenv("OFFLINE_MODE") == "true",
		GithubRepo:        getEnvDefault("GITHUB_REPO", DefaultGithubRepo),
		GithubToken:       os.Getenv("GITHUB_TOKEN"),
	}

	if _, err := os.Stat(filepath.Join(cfg.InstallDir, ".bundle-manifest")); err == nil {
		cfg.OfflineMode = true
	}

	if cfg.IsSystemd() {
		if _, err := os.Stat(cfg.InstallDir); err == nil {
			cfg.BackupDir = filepath.Join(cfg.InstallDir, "data", "backups")
		}
	}

	return cfg, nil
}

func (c *Config) IsDocker() bool  { return c.DeployMode == "docker" }
func (c *Config) IsSystemd() bool { return c.DeployMode == "systemd" }
func (c *Config) IsSQLite() bool  { return c.DBDriver == "sqlite" }

func (c *Config) Save(vars map[string]string) error {
	lines := []string{fmt.Sprintf("# Generated by nasnet-tool on %s", "auto")}
	for k, v := range vars {
		if strings.ContainsAny(v, "$`\\\"!") {
			lines = append(lines, fmt.Sprintf("%s='%s'", k, v))
		} else {
			lines = append(lines, fmt.Sprintf("%s=%s", k, v))
		}
	}
	return os.WriteFile(c.EnvFile, []byte(strings.Join(lines, "\n")+"\n"), 0600)
}

func (c *Config) SyncEnvToInstallDir() error {
	if !c.IsSystemd() {
		return nil
	}
	if _, err := os.Stat(c.InstallDir); err != nil {
		return nil
	}
	data, err := os.ReadFile(c.EnvFile)
	if err != nil {
		return err
	}
	dest := filepath.Join(c.InstallDir, ".env")
	return os.WriteFile(dest, data, 0600)
}

func getEnvDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
